spring:
  jackson:
    default-property-inclusion: non_null
  jpa:
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  auth:
    admin:
      email: admin@mail.com
      password: admin
    student:
      email: user@mail.com
      password: user
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}