spring:
  jackson:
    default-property-inclusion: non_null
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  auth:
    admin:
      email: admin@lpnu.ua
      password: admin
    student:
      email: user@mail.com
      password: user
    admin-domain: lpnu.ua

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}